repository_type: pipeline

nf_core_version: 4.1.0

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-qcflow_logo_light.png
    - docs/images/nf-core-qcflow_logo_light.png
    - docs/images/nf-core-qcflow_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-qcflow_logo_light.png
    - docs/images/nf-core-qcflow_logo_light.png
    - docs/images/nf-core-qcflow_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config

template:
  org: xiaoli-dong
  name: qcflow
  description: NGS reads qc
  author: xiaoli dong
  version: 2.0.0dev
  force: true
  outdir: ./
  skip_features:
    - igenomes
    - gpu
  is_nfcore: false
